actinia-org/actinia-docker

actinia-dev/Dockerfile

Related to https://github.com/mundialis/actinia-docker#local-dev-setup-for-actinia-core-plugins-with-vscode.

Enhance dev setup for plugins

---

actinia-alpine/Dockerfile

Update to actinia 4.0.0

---

actinia-dev/actinia.cfg
actinia-prod/actinia.cfg
actinia-ubuntu/Dockerfile
actinia-ubuntu/README.md
actinia-ubuntu/actinia.cfg
actinia-ubuntu/start.sh

- also change to GRASS GIS 8 addons
- use generic https://grass.osgeo.org/grass-stable/manuals link
Related to https://github.com/mundialis/actinia_core/issues/331

Use versionless GRASS GIS (8) instead of hardcoded grass7x

---

README.md

PR adds information for local dev-setup.

Extend description for local dev-setup

---

actinia-dev/Dockerfile

See https://github.com/mundialis/actinia_core/pull/352

Fix dev setup

---

actinia-alpine/actinia.cfg
actinia-dev/actinia.cfg
actinia-prod/actinia.cfg
actinia-ubuntu/actinia.cfg

This PR
- removes some default values from the config file
- adds basic queue config
- adds queue config examples for actinia-dev

Sync config

---

actinia-alpine/Dockerfile

... and update to latest actinia-core and actinia-api.

Use actinia-core wheel

---

actinia-alpine/Dockerfile

Update actinia-module-plugin version

---

actinia-alpine/Dockerfile_alpine_dependencies

Follow up from https://github.com/mundialis/actinia_core/pull/393
Mainly this PR removes installation from alpine packages for some python libs and adds them to be installed via pip.

Update python libs

---

actinia-dev/Dockerfile
actinia-dev/actinia.cfg
actinia-dev/interim_endpoints.csv

Save interim results on error

---

actinia-dev/actinia.cfg

See https://github.com/actinia-org/actinia-core/pull/421

Add outcommented queue config example

---

.github/workflows/docker-scheduled.yml
.github/workflows/docker.yml

See https://github.com/OSGeo/grass/pull/2921

change deprecated tag creation

---

README.md
actinia-alpine/Dockerfile
actinia-dev/Dockerfile
actinia-ubuntu/Dockerfile
actinia-ubuntu/README.md

Update
- old git references from `mundialis` to `actinia-org`
- docker image source from `mundiais/grass-py3-pdal` to `osgeo/grass-gis`

Update dockerhub and github organization names

---

actinia-alpine/Dockerfile

Fix path for actinia-core wheel

---

actinia-alpine/Dockerfile

Update dependency image version

---

actinia-alpine/Dockerfile

Update actinia alpine dependency image

---

actinia-alpine/Dockerfile_alpine_dependencies

See https://github.com/OSGeo/grass/pull/3058

Add additional GDAL drivers

---

.vscode/launch.json
.vscode/tasks.json

Update dev setup with vscode to use renamed repositories.

Adjust folder names

---

actinia-alpine/Dockerfile

actinia Image without SNAP

---

actinia-alpine/Dockerfile
actinia-alpine/Dockerfile_alpine_dependencies

See https://github.com/actinia-org/actinia-core/pull/530

Remove dependency installation via requirements.txt

---

.github/workflows/docker.yml

Only build if changes done regarding actinia-alpine + remove not needed excluding of docs

Update automatic build pipeline

---

.dockerignore
README.md
actinia-alpine/Dockerfile_alpine_dependencies
actinia-prod/start.sh
actinia-ubuntu/Dockerfile
actinia-ubuntu/start.sh

Rename location to project

---

actinia-alpine/Dockerfile
actinia-alpine/actinia.cfg
actinia-dev/actinia.cfg
actinia-prod/actinia.cfg
actinia-ubuntu/actinia.cfg

This PR adds a few more updates to the config for semantic adjustments, see https://github.com/actinia-org/actinia-core/pull/602

Update redis to kvdb
